version: "3.8"

services:
    mssql:
        image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
        ports:
            - 1433:1433
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=AcmeCorp123* # Choose a better password
        volumes: 
            - umbdrawdata:/var/opt/mssql
volumes: 
    umbdrawdata:
